FROM ghcr.io/dvakmandy/metowolf/docker-nginx

RUN apt-get update \
    && apt-get install -y php-fpm \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY nginx-php-fpm/nginx.conf /etc/nginx/nginx.conf
COPY nginx-php-fpm/default.conf /etc/nginx/conf.d/default.conf
COPY nginx-php-fpm/php-fpm.conf /etc/php/7.4/fpm/php-fpm.conf

COPY wordpress /var/www/html/wordpress

COPY nginx-php-fpm/start.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/start.sh

CMD ["/usr/local/bin/start.sh"]

