version: '3.8'

services:
  mysql:
    image: localhost:5000/mysql:latest
    container_name: mysql
    env_file:
      - ./env/mysql.env
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 3
      interval: 10s

  nginx-php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.php-fpm
    container_name: nginx-php-fpm
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - my-network
    ports:
      - "80:80"
      - "443:443"

networks:
  my-network:
    driver: bridge

